### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by nekonosukeno** [Yoraiz0r/AudioMog#4]
I noticed there is no GUI. So I [started making one](https://youtu.be/Ppq0s06fIyg). Also, I wrote a script that makes this work for DQXI-S. I will make a repo for them when they are done.

If anyone has game configurations/fixer scripts they would like to share, I can include them in a drop-down selection box when this goes live.

Nekonosuke over at the [Yggdrasil Discord](discord.gg/ntf2vW4)

**Comment by Xehanort88** [comment]
Thank you so much!

**Comment by nekonosukeno** [comment]
Just dropping off an update, I've most of the way done!

https://youtu.be/CGQqGqFHD80

**Comment by nekonosukeno** [comment]
Finally, we have a (pre) release! It's a fully functional beta version. There are more quality of life features to implement but I hope it will serve your needs! I did not include the released executable from this repository since I have not asked for/been given permission. If I am offered the permission by the author then that would be a different story. At any rate, enjoy!
[https://github.com/nekonosukeno/AudioMogGUI/releases](url)
